spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: k3m:31759
      bindings:
        eventSink-in-0:
          destination: reactive.supplier.consumer
          group: scs-reactive
        eventSupplier-out-0:
          destination: reactive.supplier.consumer
          group: scs-reactive
      function:
        definition: eventSink;eventSupplier
