spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: k3m:31759
      bindings:
        eventSink-in-0:
          destination: supplier.consumer
          group: scs
        eventSupplier-out-0:
          destination: supplier.consumer
          group: scs
      function:
        definition: eventSink;eventSupplier
